//! Golden vector tests: validate dequantization against pre-computed test vectors.
//!
//! Test vectors are generated by `scripts/gen-quant-vectors.py` and stored as
//! JSON fixtures in `tests/fixtures/quant/`. These serve as the ground truth
//! for Q4_0 and Q8_0 dequantization, matching the ggml spec.

use hologram::hologram_exec::float_dispatch::dispatch_float;
use hologram::FloatOp;
use hologram_ai_quant::{dequant_q4_0, dequant_q8_0};
use serde::Deserialize;

#[derive(Deserialize)]
struct GoldenVector {
    name: String,
    block_bytes: Vec<u8>,
    expected: Vec<f64>, // JSON numbers are f64
}

fn fixture_path(name: &str) -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop(); // crates/hologram-ai-conformance -> crates/
    p.pop(); // crates/ -> repo root
    p.push("tests/fixtures/quant");
    p.push(name);
    p
}

fn load_vectors(name: &str) -> Vec<GoldenVector> {
    let path = fixture_path(name);
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    serde_json::from_str(&data)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()))
}

// ── Q4_0 Golden Vectors ─────────────────────────────────────────────────────

#[test]
fn golden_q4_0_quant_crate() {
    let vectors = load_vectors("q4_0_golden.json");
    for v in &vectors {
        let result = dequant_q4_0(&v.block_bytes);
        assert_eq!(
            result.len(),
            v.expected.len(),
            "{}: length mismatch",
            v.name
        );
        for (i, (actual, &expected)) in result.iter().zip(v.expected.iter()).enumerate() {
            let expected = expected as f32;
            assert!(
                (actual - expected).abs() < 1e-4,
                "{}: index {i}: quant_crate={actual} golden={expected}",
                v.name
            );
        }
    }
}

#[test]
fn golden_q4_0_dispatch() {
    let vectors = load_vectors("q4_0_golden.json");
    for v in &vectors {
        let result = dispatch_float(&FloatOp::Dequantize, &[&v.block_bytes])
            .unwrap_or_else(|e| panic!("{}: dispatch failed: {e:?}", v.name));
        let actual: &[f32] = bytemuck::cast_slice(&result);
        assert_eq!(
            actual.len(),
            v.expected.len(),
            "{}: length mismatch",
            v.name
        );
        for (i, (a, &e)) in actual.iter().zip(v.expected.iter()).enumerate() {
            let e = e as f32;
            assert!(
                (a - e).abs() < 1e-4,
                "{}: index {i}: dispatch={a} golden={e}",
                v.name
            );
        }
    }
}

#[test]
fn golden_q4_0_cross_validate() {
    // Verify quant crate and dispatch agree on all golden vectors
    let vectors = load_vectors("q4_0_golden.json");
    for v in &vectors {
        let quant_result = dequant_q4_0(&v.block_bytes);
        let dispatch_result = dispatch_float(&FloatOp::Dequantize, &[&v.block_bytes])
            .unwrap_or_else(|e| panic!("{}: dispatch failed: {e:?}", v.name));
        let dispatch_f32: &[f32] = bytemuck::cast_slice(&dispatch_result);

        assert_eq!(quant_result.len(), dispatch_f32.len(), "{}: length", v.name);
        for (i, (q, d)) in quant_result.iter().zip(dispatch_f32.iter()).enumerate() {
            assert!(
                (q - d).abs() < 1e-10,
                "{}: index {i}: quant={q} dispatch={d}",
                v.name
            );
        }
    }
}

// ── Q8_0 Golden Vectors ─────────────────────────────────────────────────────

#[test]
fn golden_q8_0_quant_crate() {
    let vectors = load_vectors("q8_0_golden.json");
    for v in &vectors {
        let result = dequant_q8_0(&v.block_bytes);
        assert_eq!(
            result.len(),
            v.expected.len(),
            "{}: length mismatch",
            v.name
        );
        for (i, (actual, &expected)) in result.iter().zip(v.expected.iter()).enumerate() {
            let expected = expected as f32;
            assert!(
                (actual - expected).abs() < 1e-3,
                "{}: index {i}: quant_crate={actual} golden={expected}",
                v.name
            );
        }
    }
}
