//! Golden-vector tests (class **QZ**): validate hologram-ai's dequantization
//! against pre-computed test vectors that match the **GGML** reference (the
//! external authority). Vectors are generated by `scripts/gen-quant-vectors.py`
//! and stored as JSON under `tests/fixtures/quant/`.
//!
//! Per-kernel conformance of hologram's own ops is hologram's responsibility
//! (class KC); here we hold *our* `hologram-ai-quant` dequant to the reference,
//! independent of any hologram dispatch path.

use hologram_ai_quant::{dequant_q4_0, dequant_q8_0};
use serde::Deserialize;

#[derive(Deserialize)]
struct GoldenVector {
    name: String,
    block_bytes: Vec<u8>,
    expected: Vec<f64>, // JSON numbers are f64
}

fn fixture_path(name: &str) -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop(); // crates/hologram-ai-conformance -> crates/
    p.pop(); // crates/ -> repo root
    p.push("tests/fixtures/quant");
    p.push(name);
    p
}

fn load_vectors(name: &str) -> Vec<GoldenVector> {
    let path = fixture_path(name);
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    serde_json::from_str(&data)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()))
}

/// QZ-1: Q4_0 dequant equals the GGML reference over the golden vectors.
#[test]
fn golden_q4_0_matches_reference() {
    let vectors = load_vectors("q4_0_golden.json");
    assert!(!vectors.is_empty(), "no q4_0 golden vectors");
    for v in &vectors {
        let result = dequant_q4_0(&v.block_bytes);
        assert_eq!(
            result.len(),
            v.expected.len(),
            "{}: length mismatch",
            v.name
        );
        for (i, (actual, &expected)) in result.iter().zip(v.expected.iter()).enumerate() {
            let expected = expected as f32;
            assert!(
                (actual - expected).abs() < 1e-4,
                "{}: index {i}: dequant_q4_0={actual} golden={expected}",
                v.name
            );
        }
    }
}

/// QZ-2: Q8_0 dequant equals the GGML reference over the golden vectors.
#[test]
fn golden_q8_0_matches_reference() {
    let vectors = load_vectors("q8_0_golden.json");
    assert!(!vectors.is_empty(), "no q8_0 golden vectors");
    for v in &vectors {
        let result = dequant_q8_0(&v.block_bytes);
        assert_eq!(
            result.len(),
            v.expected.len(),
            "{}: length mismatch",
            v.name
        );
        for (i, (actual, &expected)) in result.iter().zip(v.expected.iter()).enumerate() {
            let expected = expected as f32;
            assert!(
                (actual - expected).abs() < 1e-3,
                "{}: index {i}: dequant_q8_0={actual} golden={expected}",
                v.name
            );
        }
    }
}
