//! Minimal ONNX compiler for the new hologram API.
//!
//! This is a complete rewrite using the simplified hologram API.
//! Supports basic operations with concrete shapes only.

#![deny(missing_docs)]
#![warn(clippy::all)]

use anyhow::{Context, Result};
use hologram::compiler::{CompilerConfig, compile};
use hologram::holo::HolbWriter;

// Protocol buffer types (generated by build.rs)
#[allow(clippy::all)]
#[allow(missing_docs)]
pub mod proto {
    //! ONNX protobuf definitions.
    include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
}

// Module declarations
mod builder;
mod dtypes;
mod ops;
mod parser;

// Re-export public APIs
pub use builder::build_graph;
pub use dtypes::from_onnx as dtype_from_onnx;
pub use ops::translate_node;
pub use parser::{extract_dtype, extract_shape, parse_model};

/// Compile an ONNX model to .holb format.
///
/// # Arguments
///
/// * `onnx_bytes` - Raw ONNX protobuf bytes
///
/// # Returns
///
/// Returns the compiled .holb file bytes.
///
/// # Errors
///
/// Returns error if:
/// - ONNX protobuf parsing fails
/// - Graph contains unsupported operations
/// - Compilation fails
pub fn compile_onnx(onnx_bytes: &[u8]) -> Result<Vec<u8>> {
    // Parse ONNX protobuf
    let model = parser::parse_model(onnx_bytes)?;

    // Convert to OperationGraph
    let graph = builder::build_graph(&model)?;

    // Compile to BackendPlan
    let config = CompilerConfig::default();
    let plan =
        compile(&graph, &config).map_err(|e| anyhow::anyhow!("Compilation failed: {:?}", e))?;

    // Serialize BackendPlan using rkyv 0.7 (matching hologram's version)
    let plan_bytes = rkyv::to_bytes::<_, 1024>(&plan)
        .map_err(|e| anyhow::anyhow!("Failed to serialize BackendPlan: {}", e))?;

    // Create .holb file with serialized plan
    let mut writer = HolbWriter::new();
    writer.set_graph(&plan_bytes);

    let holb_bytes = writer.build().context("Failed to build .holb file")?;

    Ok(holb_bytes)
}

#[cfg(test)]
mod tests {
    // Integration tests are in the individual modules:
    // - dtypes::tests - Data type conversion
    // - parser::tests - ONNX parsing and shape extraction
    // - ops::tests - Operation translation
    // - builder::tests - Graph building
}
