//! ONNX format support for hologram-ai.
//!
//! This crate provides parsing and compilation of ONNX models to hologram IR.
//! ONNX (Open Neural Network Exchange) is an open format for representing machine
//! learning models that allows interoperability between different ML frameworks.
//!
//! ## Features
//!
//! - **Full ONNX parser**: Parse ONNX protobuf files with complete graph extraction
//! - **Symbolic shapes**: Support for variable batch sizes and sequence lengths
//! - **Operation translators**: Convert ONNX ops to hologram IR operations
//! - **Graph partitioning**: Handle large models by splitting into partitions
//! - **Weight management**: External and embedded weight storage options
//!
//! ## Example
//!
//! ```ignore
//! use hologram_ai_onnx::{OnnxCompiler, OnnxConfig};
//! use std::fs;
//!
//! let compiler = OnnxCompiler::new();
//! let onnx_bytes = fs::read("model.onnx")?;
//! let (holo_bytes, weight_bytes) = compiler.compile(&onnx_bytes)?;
//! ```

#![deny(missing_docs)]
#![warn(clippy::all)]

// Protocol buffer types (generated by build.rs)
#[allow(clippy::all)]
#[allow(missing_docs)]
pub mod proto {
    //! ONNX protobuf definitions.
    include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
}

// Core modules
pub mod core;
pub mod translators;

// Re-export main types at crate root for convenience
pub use core::{
    Dim, GraphPartition, GraphPartitioner, OnnxConfig, OnnxError, Result, Shape, SymbolicShape,
    WeightData, extract_opset_version, parse_model, translate_graph_to_ir, validate_model,
};

// Re-export hologram-ir types for convenience
pub use hologram::ir::{GraphBuilder, NodeIndex, OperationGraph};

/// Main ONNX compiler interface.
///
/// Provides high-level API for compiling ONNX models to .holo format with
/// full ISA optimization support.
///
/// # Examples
///
/// ```ignore
/// use hologram_ai_onnx::{OnnxCompiler, OnnxConfig};
/// use std::fs;
///
/// // Use default configuration
/// let compiler = OnnxCompiler::new();
///
/// let onnx_bytes = fs::read("model.onnx")?;
/// let (holo_bytes, weight_bytes) = compiler.compile(&onnx_bytes)?;
///
/// fs::write("model.holo", holo_bytes)?;
/// fs::write("model.weights", weight_bytes)?;
/// ```
pub struct OnnxCompiler {
    config: OnnxConfig,
}

impl OnnxCompiler {
    /// Create a new compiler with default configuration.
    ///
    /// Default settings:
    /// - Weight threshold: 4096 bytes
    /// - Partitioning: disabled
    /// - Partition size: 500 nodes
    /// - Conv2D decomposition: enabled
    /// - Pooling decomposition: enabled
    /// - Memory budget: unlimited
    pub fn new() -> Self {
        Self {
            config: OnnxConfig::default(),
        }
    }

    /// Create a new compiler with custom configuration.
    pub fn with_config(config: OnnxConfig) -> Self {
        Self { config }
    }

    /// Compile ONNX model to .holo format.
    ///
    /// This method performs the complete compilation pipeline:
    /// 1. Parse ONNX protobuf
    /// 2. Translate to IR with symbolic shapes
    /// 3. Apply hologram-ir graph building
    /// 4. Serialize to .holo + .weights files
    ///
    /// # Arguments
    ///
    /// * `onnx_bytes` - Raw ONNX model bytes (protobuf format)
    ///
    /// # Returns
    ///
    /// A tuple of `(holo_bytes, weight_bytes)`:
    /// - `holo_bytes`: Serialized OperationGraph for the .holo file
    /// - `weight_bytes`: External weight data for the .weights file (may be empty)
    pub fn compile(&self, onnx_bytes: &[u8]) -> Result<(Vec<u8>, Vec<u8>)> {
        use tracing::{debug, info};

        info!("Starting ONNX compilation");

        // Step 1: Parse and validate ONNX model
        debug!("Parsing ONNX protobuf");
        let model = parse_model(onnx_bytes)?;
        validate_model(&model)?;
        let opset_version = core::extract_opset_version(&model);
        info!("ONNX opset version: {}", opset_version);

        // Get the graph
        let graph = model
            .graph
            .as_ref()
            .ok_or_else(|| OnnxError::InvalidModel("Model has no graph".into()))?;

        // Check if partitioning is needed
        if self.config.enable_partitioning && graph.node.len() > self.config.partition_size {
            info!(
                "Large graph detected ({} nodes), using partitioning",
                graph.node.len()
            );
            return self.compile_partitioned(onnx_bytes);
        }

        // Step 2: Translate ONNX → IR with symbolic shapes
        debug!("Translating ONNX to IR");
        let ir_func = translate_graph_to_ir(graph)?;
        info!("IR translation complete");

        // Step 3: Compile to BackendPlan using hologram-compiler
        debug!("Compiling IR to BackendPlan");

        let backend_type = hologram::BackendType::Cpu;
        let mut plan = hologram::compiler::compile_ir(&ir_func, backend_type)
            .map_err(|e| OnnxError::IrTranslationError(format!("Failed to compile IR: {:?}", e)))?;

        // Extract constant_data to external weights file if above threshold
        let weight_bytes = if plan.constant_data.len() > self.config.weight_threshold {
            info!(
                "Extracting {} bytes of constant data to external weights file (threshold: {} bytes)",
                plan.constant_data.len(),
                self.config.weight_threshold
            );
            std::mem::take(&mut plan.constant_data)
        } else {
            debug!(
                "Keeping {} bytes of constant data embedded in .holo file",
                plan.constant_data.len()
            );
            Vec::new()
        };

        debug!("Serializing BackendPlan to .holo format");
        let holo_bytes = serialize_backend_plan(&plan)?;

        info!(
            "Compilation complete: {} bytes .holo, {} bytes .weights",
            holo_bytes.len(),
            weight_bytes.len()
        );

        Ok((holo_bytes, weight_bytes))
    }

    /// Compile large model using graph partitioning.
    pub fn compile_partitioned(&self, onnx_bytes: &[u8]) -> Result<(Vec<u8>, Vec<u8>)> {
        use tracing::{debug, info};

        info!("Starting partitioned compilation");

        // Parse model
        let model = parse_model(onnx_bytes)?;
        validate_model(&model)?;

        let graph = model
            .graph
            .as_ref()
            .ok_or_else(|| OnnxError::InvalidModel("Model has no graph".into()))?;

        // Analyze partitioning structure
        let partitioner = core::GraphPartitioner::new();
        let partitions = partitioner.partition(graph)?;
        info!(
            "Analyzed graph: {} nodes split into {} partitions",
            graph.node.len(),
            partitions.len()
        );

        // Compile the full graph
        debug!("Translating ONNX to IR");
        let ir_func = translate_graph_to_ir(graph)?;

        // Compile to BackendPlan using hologram-compiler
        debug!("Compiling IR to BackendPlan");
        let backend_type = hologram::BackendType::Cpu;
        let mut plan = hologram::compiler::compile_ir(&ir_func, backend_type)
            .map_err(|e| OnnxError::IrTranslationError(format!("Failed to compile IR: {:?}", e)))?;

        // Extract constant_data to external weights file if above threshold
        let weight_bytes = if plan.constant_data.len() > self.config.weight_threshold {
            info!(
                "Extracting {} bytes of constant data to external weights file",
                plan.constant_data.len()
            );
            std::mem::take(&mut plan.constant_data)
        } else {
            Vec::new()
        };

        let holo_bytes = serialize_backend_plan(&plan)?;

        info!(
            "Partitioned compilation complete: {} bytes .holo, {} bytes .weights",
            holo_bytes.len(),
            weight_bytes.len()
        );

        Ok((holo_bytes, weight_bytes))
    }

    /// Compile ONNX model to a unified bundle (HOLB format).
    pub fn compile_to_bundle(&self, onnx_bytes: &[u8]) -> Result<Vec<u8>> {
        use tracing::{debug, info};

        info!("Starting ONNX compilation to unified bundle");

        // Step 1: Parse and validate ONNX model
        debug!("Parsing ONNX protobuf");
        let model = parse_model(onnx_bytes)?;
        validate_model(&model)?;
        let opset_version = core::extract_opset_version(&model);
        info!("ONNX opset version: {}", opset_version);

        // Get the graph
        let graph = model
            .graph
            .as_ref()
            .ok_or_else(|| OnnxError::InvalidModel("Model has no graph".into()))?;

        // Step 2: Translate ONNX → IR with symbolic shapes
        debug!("Translating ONNX to IR");
        let ir_func = translate_graph_to_ir(graph)?;
        info!("IR translation complete");

        // Step 3: Compile to BackendPlan using hologram-compiler
        debug!("Compiling IR to BackendPlan");
        let backend_type = hologram::BackendType::Cpu;
        let mut plan = hologram::compiler::compile_ir(&ir_func, backend_type)
            .map_err(|e| OnnxError::IrTranslationError(format!("Failed to compile IR: {:?}", e)))?;

        // Extract weights from plan (they'll be embedded in the bundle)
        let weight_bytes = std::mem::take(&mut plan.constant_data);
        info!(
            "Extracted {} bytes of weights for bundle",
            weight_bytes.len()
        );

        // Step 4: Serialize plan to HOLP format (without weights)
        debug!("Serializing BackendPlan");
        let graph_bytes = serialize_backend_plan(&plan)?;

        // Step 5: Create unified bundle
        debug!("Creating unified bundle");
        let mut writer = core::UnifiedBundleWriter::new();
        writer.set_graph_bytes(graph_bytes);
        writer.set_weights_bytes(weight_bytes);
        let bundle = writer.finish();

        info!(
            "Compilation to bundle complete: {} bytes total",
            bundle.len()
        );

        Ok(bundle)
    }
}

impl Default for OnnxCompiler {
    fn default() -> Self {
        Self::new()
    }
}

/// Serialize a BackendPlan to .holo format bytes.
fn serialize_backend_plan(plan: &hologram::backend::BackendPlan) -> Result<Vec<u8>> {
    // Convert to serializable form (function pointers → kernel IDs)
    let serializable = plan.to_serializable();

    // Serialize using rkyv
    let plan_bytes = rkyv::to_bytes::<rkyv::rancor::Error>(&serializable)
        .map(|bytes| bytes.to_vec())
        .map_err(|e| {
            OnnxError::IrTranslationError(format!("Failed to serialize BackendPlan: {}", e))
        })?;

    // Prepend magic bytes
    let mut holo_bytes = Vec::with_capacity(4 + plan_bytes.len());
    holo_bytes.extend_from_slice(&hologram::compiler::HOLO_MAGIC);
    holo_bytes.extend_from_slice(&plan_bytes);

    Ok(holo_bytes)
}

/// Convenience function to compile ONNX model to .holo format.
pub fn compile_onnx(onnx_bytes: &[u8]) -> Result<(Vec<u8>, Vec<u8>)> {
    let compiler = OnnxCompiler::new();
    compiler.compile(onnx_bytes)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_onnx_compiler_new() {
        let compiler = OnnxCompiler::new();
        assert_eq!(compiler.config.weight_threshold, 4096);
    }

    #[test]
    fn test_onnx_compiler_default() {
        let compiler = OnnxCompiler::default();
        assert_eq!(compiler.config.weight_threshold, 4096);
    }

    #[test]
    fn test_onnx_compiler_with_config() {
        let config = OnnxConfig {
            weight_threshold: 8192,
            ..Default::default()
        };
        let compiler = OnnxCompiler::with_config(config);
        assert_eq!(compiler.config.weight_threshold, 8192);
    }
}
