//! # hologram-onnx
//!
//! Production ONNX runtime for hologram with full ISA optimization support.
//!
//! This crate provides a complete ONNX compilation pipeline that leverages hologram's
//! Instruction Set Architecture (ISA) for maximum performance:
//!
//! - **LOOP instructions**: O(1) space complexity (5,461x instruction reduction)
//! - **PhiCoordinate addressing**: Cache-resident boundary pool addressing for 5-10x speedup
//! - **ClassMap fusion**: O(1) element-wise operation composition using 96-byte lookup tables
//! - **SIMD vectorization**: Provided by hologram-backend
//! - **Im2col + GEMM decomposition**: Conv2D optimization via hologram's decomposition pass
//!
//! ## Architecture
//!
//! ```text
//! ONNX ModelProto
//!     ↓ [Parser]
//! ONNX Graph + Initializers
//!     ↓ [Translator]
//! IR OperationGraph (with symbolic shapes)
//!     ↓ [hologram-ir]
//! OperationGraph + WeightData
//!     ↓ [Serialize]
//! model.holo + model.weights
//! ```
//!
//! ## Features
//!
//! - **Symbolic shapes**: Full support for variable batch sizes and sequence lengths
//! - **Memory efficient**: Weight streaming and graph partitioning for large models (3000+ nodes)
//! - **Config-driven**: TOML pipeline configs for multi-modal outputs (text→image, text→audio, text→text)
//! - **Feature-gated handlers**: `image-output`, `audio-output`, `text-output`
//!
//! ## Usage
//!
//! ### Basic Compilation
//!
//! ```no_run
//! use hologram_onnx::compile_onnx;
//! use std::fs;
//!
//! # fn main() -> Result<(), Box<dyn std::error::Error>> {
//! // Load ONNX model
//! let onnx_bytes = fs::read("model.onnx")?;
//!
//! // Compile to .holo format
//! let (holo_bytes, weight_bytes) = compile_onnx(&onnx_bytes)?;
//!
//! // Write output files
//! fs::write("model.holo", holo_bytes)?;
//! if !weight_bytes.is_empty() {
//!     fs::write("model.weights", weight_bytes)?;
//! }
//! # Ok(())
//! # }
//! ```
//!
//! ### Advanced Compilation with Config
//!
//! ```no_run
//! use hologram_onnx::{OnnxCompiler, OnnxConfig};
//! use std::fs;
//!
//! # fn main() -> Result<(), Box<dyn std::error::Error>> {
//! let config = OnnxConfig {
//!     weight_threshold: 4096,        // External storage threshold
//!     enable_partitioning: true,     // For large models
//!     partition_size: 500,            // Nodes per partition
//!     decompose_conv2d: true,         // Conv2D → Im2col+GEMM
//!     decompose_pooling: true,        // Pooling decomposition
//!     pack_weights: true,             // Use packed weights when supported
//!     memory_budget: Some(8 * 1024),  // 8 GB limit
//!     enable_resize_upscaling: true,  // Enable Resize upscaling
//! };
//!
//! let compiler = OnnxCompiler::with_config(config);
//! let onnx_bytes = fs::read("large_model.onnx")?;
//! let (holo_bytes, weight_bytes) = compiler.compile(&onnx_bytes)?;
//! # Ok(())
//! # }
//! ```

#![deny(missing_docs)]
#![warn(clippy::all)]

// Protocol buffer types (generated by build.rs)
#[allow(clippy::all)]
#[allow(missing_docs)]
pub mod proto {
    //! ONNX protobuf definitions.
    include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
}

// Core modules
pub mod cli;
pub mod config;
pub mod core;
pub mod ops;
pub mod runtime;
pub mod tokenizers;

// Re-export main types at crate root for convenience
pub use core::{
    Dim, GraphPartition, GraphPartitioner, OnnxConfig, OnnxError, Result, Shape, SymbolicShape,
    WeightData, apply_ir_decomposition, extract_opset_version, parse_model, translate_graph_to_ir,
    validate_model,
};

// Re-export hologram-ir types for convenience
pub use hologram::ir::{GraphBuilder, NodeIndex, OperationGraph};

/// Main ONNX compiler interface.
///
///  Provides high-level API for compiling ONNX models to .holo format with
/// full ISA optimization support.
///
/// # Examples
///
/// ```no_run
/// use hologram_onnx::{OnnxCompiler, OnnxConfig};
/// use std::fs;
///
/// # fn main() -> Result<(), Box<dyn std::error::Error>> {
/// // Use default configuration
/// let compiler = OnnxCompiler::new();
///
/// let onnx_bytes = fs::read("model.onnx")?;
/// let (holo_bytes, weight_bytes) = compiler.compile(&onnx_bytes)?;
///
/// fs::write("model.holo", holo_bytes)?;
/// fs::write("model.weights", weight_bytes)?;
/// # Ok(())
/// # }
/// ```
pub struct OnnxCompiler {
    config: OnnxConfig,
}

impl OnnxCompiler {
    /// Create a new compiler with default configuration.
    ///
    /// Default settings:
    /// - Weight threshold: 4096 bytes
    /// - Partitioning: disabled
    /// - Partition size: 500 nodes
    /// - Conv2D decomposition: enabled
    /// - Pooling decomposition: enabled
    /// - Memory budget: unlimited
    pub fn new() -> Self {
        Self {
            config: OnnxConfig::default(),
        }
    }

    /// Create a new compiler with custom configuration.
    ///
    /// # Arguments
    ///
    /// * `config` - Custom compilation configuration
    ///
    /// # Examples
    ///
    /// ```no_run
    /// use hologram_onnx::{OnnxCompiler, OnnxConfig};
    ///
    /// let config = OnnxConfig {
    ///     weight_threshold: 8192,
    ///     enable_partitioning: true,
    ///     partition_size: 1000,
    ///     decompose_conv2d: true,
    ///     decompose_pooling: true,
    ///     pack_weights: true,
    ///     memory_budget: Some(16 * 1024), // 16 GB
    ///     enable_resize_upscaling: true,
    /// };
    ///
    /// let compiler = OnnxCompiler::with_config(config);
    /// ```
    pub fn with_config(config: OnnxConfig) -> Self {
        Self { config }
    }

    /// Compile ONNX model to .holo format.
    ///
    /// This method performs the complete compilation pipeline:
    /// 1. Parse ONNX protobuf
    /// 2. Translate to IR with symbolic shapes
    /// 3. Apply hologram-ir graph building
    /// 4. Serialize to .holo + .weights files
    ///
    /// # Arguments
    ///
    /// * `onnx_bytes` - Raw ONNX model bytes (protobuf format)
    ///
    /// # Returns
    ///
    /// A tuple of `(holo_bytes, weight_bytes)`:
    /// - `holo_bytes`: Serialized OperationGraph for the .holo file
    /// - `weight_bytes`: External weight data for the .weights file (may be empty)
    ///
    /// # Errors
    ///
    /// Returns [`OnnxError`] if:
    /// - ONNX protobuf parsing fails
    /// - Unsupported operations are encountered
    /// - Shape inference fails
    /// - Symbolic shape validation fails
    /// - Memory budget is exceeded
    pub fn compile(&self, onnx_bytes: &[u8]) -> Result<(Vec<u8>, Vec<u8>)> {
        use tracing::{debug, info};

        info!("Starting ONNX compilation");

        // Step 1: Parse and validate ONNX model
        debug!("Parsing ONNX protobuf");
        let model = parse_model(onnx_bytes)?;
        validate_model(&model)?;
        let opset_version = core::extract_opset_version(&model);
        info!("ONNX opset version: {}", opset_version);

        // Get the graph
        let graph = model
            .graph
            .as_ref()
            .ok_or_else(|| OnnxError::InvalidModel("Model has no graph".into()))?;

        // Check if partitioning is needed
        if self.config.enable_partitioning && graph.node.len() > self.config.partition_size {
            info!(
                "Large graph detected ({} nodes), using partitioning",
                graph.node.len()
            );
            return self.compile_partitioned(onnx_bytes);
        }

        // Step 2: Translate ONNX → IR with symbolic shapes
        debug!("Translating ONNX to IR");
        let ir_func = translate_graph_to_ir(graph)?;
        info!("IR translation complete");

        // Step 3: Compile to BackendPlan using hologram-compiler
        debug!("Compiling IR to BackendPlan");

        // ir_func is already hologram_ir::OperationGraph (aliased as IRFunction)
        let backend_type = hologram::BackendType::Cpu; // Default to CPU
        let mut plan = hologram::compiler::compile_ir(&ir_func, backend_type)
            .map_err(|e| OnnxError::IrTranslationError(format!("Failed to compile IR: {:?}", e)))?;

        // Extract constant_data to external weights file if above threshold.
        // The executor will use memory-mapped access to load these on demand.
        let weight_bytes = if plan.constant_data.len() > self.config.weight_threshold {
            info!(
                "Extracting {} bytes of constant data to external weights file (threshold: {} bytes)",
                plan.constant_data.len(),
                self.config.weight_threshold
            );
            // Take constant_data out of plan, leaving empty Vec in its place.
            // BufferRef::Constant offsets remain valid since they index into the weights file.
            std::mem::take(&mut plan.constant_data)
        } else {
            debug!(
                "Keeping {} bytes of constant data embedded in .holo file",
                plan.constant_data.len()
            );
            Vec::new()
        };

        debug!("Serializing BackendPlan to .holo format");
        let holo_bytes = serialize_backend_plan(&plan)?;

        info!(
            "Compilation complete: {} bytes .holo, {} bytes .weights",
            holo_bytes.len(),
            weight_bytes.len()
        );

        Ok((holo_bytes, weight_bytes))
    }

    /// Compile large model using graph partitioning.
    ///
    /// This method is automatically used for models with >500 nodes
    /// when `enable_partitioning` is true in the configuration.
    ///
    /// Graph partitioning avoids OOM errors by compiling the model
    /// in chunks, then merging the results.
    pub fn compile_partitioned(&self, onnx_bytes: &[u8]) -> Result<(Vec<u8>, Vec<u8>)> {
        use tracing::{debug, info};

        info!("Starting partitioned compilation");

        // Parse model
        let model = parse_model(onnx_bytes)?;
        validate_model(&model)?;

        let graph = model
            .graph
            .as_ref()
            .ok_or_else(|| OnnxError::InvalidModel("Model has no graph".into()))?;

        // Analyze partitioning structure
        let partitioner = core::GraphPartitioner::new();
        let partitions = partitioner.partition(graph)?;
        info!(
            "Analyzed graph: {} nodes split into {} partitions",
            graph.node.len(),
            partitions.len()
        );

        // Compile the full graph (partitioner is mainly for analysis/memory management)
        debug!("Translating ONNX to IR");
        let ir_func = translate_graph_to_ir(graph)?;

        // Compile to BackendPlan using hologram-compiler
        debug!("Compiling IR to BackendPlan");
        let backend_type = hologram::BackendType::Cpu; // Default to CPU
        let mut plan = hologram::compiler::compile_ir(&ir_func, backend_type)
            .map_err(|e| OnnxError::IrTranslationError(format!("Failed to compile IR: {:?}", e)))?;

        // Extract constant_data to external weights file if above threshold
        let weight_bytes = if plan.constant_data.len() > self.config.weight_threshold {
            info!(
                "Extracting {} bytes of constant data to external weights file",
                plan.constant_data.len()
            );
            std::mem::take(&mut plan.constant_data)
        } else {
            Vec::new()
        };

        let holo_bytes = serialize_backend_plan(&plan)?;

        info!(
            "Partitioned compilation complete: {} bytes .holo, {} bytes .weights",
            holo_bytes.len(),
            weight_bytes.len()
        );

        Ok((holo_bytes, weight_bytes))
    }

    /// Compile ONNX model to a unified bundle (HOLB format).
    ///
    /// This creates a single-file bundle with embedded weights. The weights
    /// section is page-aligned for efficient memory-mapping when loaded.
    ///
    /// # Arguments
    /// * `onnx_bytes` - Raw bytes of the ONNX model protobuf
    ///
    /// # Returns
    /// A `Vec<u8>` containing the complete bundle (graph + weights)
    ///
    /// # Errors
    /// Returns [`OnnxError`] if compilation fails.
    pub fn compile_to_bundle(&self, onnx_bytes: &[u8]) -> Result<Vec<u8>> {
        use tracing::{debug, info};

        info!("Starting ONNX compilation to unified bundle");

        // Step 1: Parse and validate ONNX model
        debug!("Parsing ONNX protobuf");
        let model = parse_model(onnx_bytes)?;
        validate_model(&model)?;
        let opset_version = core::extract_opset_version(&model);
        info!("ONNX opset version: {}", opset_version);

        // Get the graph
        let graph = model
            .graph
            .as_ref()
            .ok_or_else(|| OnnxError::InvalidModel("Model has no graph".into()))?;

        // Step 2: Translate ONNX → IR with symbolic shapes
        debug!("Translating ONNX to IR");
        let ir_func = translate_graph_to_ir(graph)?;
        info!("IR translation complete");

        // Step 3: Compile to BackendPlan using hologram-compiler
        debug!("Compiling IR to BackendPlan");
        let backend_type = hologram::BackendType::Cpu;
        let mut plan = hologram::compiler::compile_ir(&ir_func, backend_type)
            .map_err(|e| OnnxError::IrTranslationError(format!("Failed to compile IR: {:?}", e)))?;

        // Extract weights from plan (they'll be embedded in the bundle)
        let weight_bytes = std::mem::take(&mut plan.constant_data);
        info!("Extracted {} bytes of weights for bundle", weight_bytes.len());

        // Step 4: Serialize plan to HOLP format (without weights)
        debug!("Serializing BackendPlan");
        let graph_bytes = serialize_backend_plan(&plan)?;

        // Step 5: Create unified bundle
        debug!("Creating unified bundle");
        let mut writer = core::UnifiedBundleWriter::new();
        writer.set_graph_bytes(graph_bytes);
        writer.set_weights_bytes(weight_bytes);
        let bundle = writer.finish();

        info!(
            "Compilation to bundle complete: {} bytes total ({} bytes graph + weights)",
            bundle.len(),
            bundle.len()
        );

        Ok(bundle)
    }
}

impl Default for OnnxCompiler {
    fn default() -> Self {
        Self::new()
    }
}

/// Serialize a BackendPlan to .holo format bytes.
///
/// This function:
/// 1. Converts BackendPlan to SerializableBackendPlan (kernel IDs)
/// 2. Serializes using rkyv zero-copy format
/// 3. Prepends HOLO_MAGIC bytes ([b'H', b'O', b'L', b'P'])
///
/// The resulting bytes can be written to a .holo file and later loaded
/// by both hologram and hologram-onnx runtimes.
fn serialize_backend_plan(plan: &hologram::backend::BackendPlan) -> Result<Vec<u8>> {
    // Convert to serializable form (function pointers → kernel IDs)
    let serializable = plan.to_serializable();

    // Serialize using rkyv
    let plan_bytes = rkyv::to_bytes::<rkyv::rancor::Error>(&serializable)
        .map(|bytes| bytes.to_vec())
        .map_err(|e| OnnxError::IrTranslationError(format!("Failed to serialize BackendPlan: {}", e)))?;

    // Prepend magic bytes
    let mut holo_bytes = Vec::with_capacity(4 + plan_bytes.len());
    holo_bytes.extend_from_slice(&hologram::compiler::HOLO_MAGIC);
    holo_bytes.extend_from_slice(&plan_bytes);

    Ok(holo_bytes)
}

/// Convenience function to compile ONNX model to .holo format.
///
/// This function provides a simple interface for basic ONNX compilation
/// with default settings. For advanced usage with custom configuration,
/// use [`OnnxCompiler::with_config`].
///
/// # Arguments
///
/// * `onnx_bytes` - Raw ONNX model bytes (protobuf format)
///
/// # Returns
///
/// A tuple of `(holo_bytes, weight_bytes)`:
/// - `holo_bytes`: Serialized OperationGraph for the .holo file
/// - `weight_bytes`: External weight data for the .weights file (may be empty)
///
/// # Errors
///
/// Returns [`OnnxError`] if:
/// - ONNX protobuf parsing fails
/// - Unsupported operations are encountered
/// - Shape inference fails
/// - Symbolic shape validation fails
/// - Memory budget is exceeded during compilation
///
/// # Examples
///
/// ```no_run
/// use hologram_onnx::compile_onnx;
/// use std::fs;
///
/// # fn main() -> Result<(), Box<dyn std::error::Error>> {
/// let onnx_bytes = fs::read("model.onnx")?;
/// let (holo_bytes, weight_bytes) = compile_onnx(&onnx_bytes)?;
///
/// fs::write("model.holo", holo_bytes)?;
/// if !weight_bytes.is_empty() {
///     fs::write("model.weights", weight_bytes)?;
/// }
/// # Ok(())
/// # }
/// ```
pub fn compile_onnx(onnx_bytes: &[u8]) -> Result<(Vec<u8>, Vec<u8>)> {
    let compiler = OnnxCompiler::new();
    compiler.compile(onnx_bytes)
}
