import { useEffect, useMemo, useRef, useState, useSyncExternalStore } from "react";
import { renderChatTemplate } from "../chatTemplate";
import {
  CompiledArchive,
  loadSessionMeta,
  type ModelChat,
  KnownModelStatus,
  cancelGeneration,
  generate,
  listCompiledArchives,
  listKnownModels,
} from "../ipc";
import { chatStream } from "../chatStream";
import { countTokens } from "../holo";
import { MessageBody } from "../components/MessageBody";

interface Message {
  role: "user" | "assistant";
  text: string;
}

// Strip tokenizer special tokens (e.g. `<|im_end|>`, `<|endoftext|>`),
// turn `<br>` into newlines, drop stray HTML tags, and remove the CLI's
// trailing benchmark summary line before display. Models occasionally
// surface these in their output; the raw stream is still preserved in
// the Logs tab.
//
// Special-token regex matches any of `<|name|>`, `<|name|`, `<|name` — the
// CLI's stop-string detection often cuts the trailing `>` (and sometimes
// the trailing `|`) before suppressing emission, so the truncated forms
// still show up in the streamed text. Restricting the body to
// `[A-Za-z0-9_]` avoids chewing up unrelated `<|` sequences from user
// content.
//
// HTML-tag stripping kicks in *outside* fenced code blocks. Base
// (non-instruct) models tend to regurgitate scraped HTML (`<div …>`,
// `<a href=…>`, `</p>`) which clutters the bubble; legitimate HTML inside
// triple-backtick code blocks is preserved so users can ask "show me an
// `<input>`" and still see the markup.
//
// Stats-line regex matches the CLI's `\n\n[N tokens | TTFT Xms | decode N
// tok in Xs (Xtok/s) | weights X GiB]` footer. Leaving it in would both
// clutter the bubble *and* be replayed verbatim into the next multi-turn
// prompt as part of the prior assistant message.
function cleanAssistantText(s: string): string {
  let out = s;
  out = out.replace(/<\|[A-Za-z0-9_]*\|?>?/g, "");
  out = out.replace(/<br\s*\/?>/gi, "\n");
  out = stripHtmlOutsideCodeBlocks(out);
  out = stripBaseModelArtifactsOutsideCodeBlocks(out);
  out = out.replace(/\n*\[\d+ tokens \| TTFT[^\]\n]*\]\s*$/g, "");
  return out.trimEnd();
}

// Split the text on triple-backtick fences (and `~~~` fences) so that
// HTML/XML tags inside fenced code blocks are left intact, while tags in
// prose are stripped. Odd-indexed segments are the fenced blocks
// themselves (preserved verbatim).
function stripHtmlOutsideCodeBlocks(s: string): string {
  const parts = s.split(/(```[\s\S]*?```|~~~[\s\S]*?~~~)/g);
  const tagPattern = /<\/?[A-Za-z][A-Za-z0-9-]*(?:\s+[^<>]*)?\/?>/g;
  return parts
    .map((part, i) => (i % 2 === 1 ? part : part.replace(tagPattern, "")))
    .join("");
}

// Strip a few classes of training-data leakage that base (non-instruct)
// models tend to emit. None of these are valid markdown, none are
// generated by chat-tuned models in normal use, and all of them clutter
// the bubble. Code fences are preserved as-is.
//   - `\start\foo{...}\endfoo`   — Jupyter notebook export markers
//   - `\start\foo{...}\endfoo>`  — same, with stray angle bracket
//   - `\command{...}`            — bare LaTeX-style commands that aren't
//                                    inside an actual `$…$` math block
//   - stray closing `>` with no matching `<` on the line
function stripBaseModelArtifactsOutsideCodeBlocks(s: string): string {
  const parts = s.split(/(```[\s\S]*?```|~~~[\s\S]*?~~~|\$\$[\s\S]*?\$\$|\$[^\n$]+\$)/g);
  return parts
    .map((part, i) => {
      if (i % 2 === 1) return part;
      let p = part;
      p = p.replace(/\\start\\[A-Za-z]+\{[^}]*\}\\end[A-Za-z]+>?/g, "");
      p = p.replace(/(^|\s)\\[A-Za-z]+\{[^}]*\}/g, "$1");
      p = p.replace(/(^|\s)>+(\s|$)/g, "$1$2");
      return p;
    })
    .join("");
}

// Generic "between turns" separator for archives that aren't matched against
// any catalogue entry. The plain `User:` / `Assistant:` labelling is a format
// most chat-tuned models recognise even when their canonical template uses
// different delimiters — it gives us memory by default rather than no memory.
const GENERIC_TURN_SEPARATOR = "\n\nAssistant: {response}\n\nUser: ";

// Build the `{prompt}` slot for a multi-turn conversation. The compile-time
// prompt template wraps the *outer* user/assistant turn; we inject prior
// turns inside the slot using `separator` (which carries `{response}`
// substituted with the prior assistant message).
//
// `messages` contains every prior user+assistant pair *plus* the new pending
// user message at the tail. With only the pending message (no history),
// this returns just the user text — same as a single-turn prompt.
function buildMultiTurnPrompt(messages: Message[], separator: string): string {
  if (messages.length === 0) return "";
  if (messages.length === 1) return messages[0].text;
  // Pair off prior user/assistant turns. A trailing user message without a
  // matching assistant reply is the *new* turn the model is about to answer.
  const parts: string[] = [];
  for (let i = 0; i + 1 < messages.length; i += 2) {
    const u = messages[i];
    const a = messages[i + 1];
    if (u.role !== "user" || a.role !== "assistant") {
      // Out-of-order — fall back to single-turn rather than emit nonsense.
      return messages[messages.length - 1].text;
    }
    parts.push(u.text);
    parts.push(separator.replace("{response}", a.text));
  }
  // Final pending user turn (the message we're about to send).
  const last = messages[messages.length - 1];
  if (last.role !== "user") return messages[messages.length - 1].text;
  parts.push(last.text);
  return parts.join("");
}

// Render the conversation with the MODEL'S OWN chat template (from its
// tokenizer_config.json), the way transformers does — so ANY instruct model
// gets its correct prompt format and end token, never a hard-coded per-model
// template. Returns `null` when the model ships no chat template (a base model)
// or the template can't render, and the caller falls back to the catalogue's
// prompt-template plumbing.
function renderChat(history: Message[], meta: ModelChat | null): { prompt: string; stop: string[] } | null {
  return renderChatTemplate(
    meta?.chatTemplate,
    history.map((m) => ({ role: m.role, content: m.text })),
    { eosToken: meta?.eosToken, bosToken: meta?.bosToken },
  );
}

// Resolve which catalogue entry (if any) corresponds to the selected
// archive path, by matching the archive's filename stem against the
// catalogue id, or its parent dir against the model's HF repo name.
function findKnownModel(
  archivePath: string,
  known: KnownModelStatus[],
): KnownModelStatus | undefined {
  const lower = archivePath.toLowerCase();
  return known.find((m) => {
    if (m.compiledArchive && m.compiledArchive === archivePath) return true;
    if (lower.includes(`/${m.id.toLowerCase()}.holo`)) return true;
    const repoName = m.hfId.split("/").pop()?.toLowerCase();
    if (repoName && lower.includes(`/${repoName}/`)) return true;
    return false;
  });
}

export function Chat() {
  const [archives, setArchives] = useState<CompiledArchive[]>([]);
  const [archive, setArchive] = useState<string>("");
  const [knownModels, setKnownModels] = useState<KnownModelStatus[]>([]);
  const [prompt, setPrompt] = useState("");

  const [temperature, setTemperature] = useState(0.7);
  const [running, setRunning] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [sessionMeta, setSessionMeta] = useState<
    ({ contextLength: number | null; tokenizer?: Uint8Array } & ModelChat) | null
  >(null);
  const transcriptRef = useRef<HTMLDivElement>(null);

  // The in-flight generation lives in a module-level store, not this component:
  // token deltas + startup narration accumulate whichever route is mounted, so
  // watching the Logs page mid-generation no longer strands the bubble. `Chat`
  // reads the live snapshot and renders it; the completed turn is committed by
  // `onSend` (and persisted to localStorage) independent of mount state.
  const stream = useSyncExternalStore(chatStream.subscribe, chatStream.getSnapshot);
  const inFlight = stream.generating && stream.archive === archive;
  const streamingText = inFlight ? cleanAssistantText(stream.text) : "";

  useEffect(() => {
    listCompiledArchives().then((a) => {
      setArchives(a);
      if (a.length && !archive) {
        // Restore the model selected before the last reload, if still present.
        const saved = localStorage.getItem("hologram_chat_archive");
        setArchive(saved && a.some((x) => x.path === saved) ? saved : a[0].path);
      }
    });
    listKnownModels().then(setKnownModels);
  }, []);

  // Persistence across reloads: remember the selected model and carry each
  // model's conversation. Switching models loads THAT model's history; a reload
  // restores it. Kept in localStorage (data, never code) keyed by archive.
  useEffect(() => {
    if (!archive) return;
    localStorage.setItem("hologram_chat_archive", archive);
    try {
      const saved = localStorage.getItem(`hologram_chat:${archive}`);
      setMessages(saved ? (JSON.parse(saved) as Message[]) : []);
    } catch {
      setMessages([]);
    }
  }, [archive]);

  useEffect(() => {
    if (!archive) return;
    try {
      localStorage.setItem(`hologram_chat:${archive}`, JSON.stringify(messages));
    } catch {
      // Storage full/unavailable — the session still works in memory.
    }
  }, [messages, archive]);

  // Load the model's own context window + tokenizer once per archive (never in
  // the send hot path). This is what bounds the session — the model's limits.
  useEffect(() => {
    if (!archive) {
      setSessionMeta(null);
      return;
    }
    let live = true;
    loadSessionMeta(archive)
      .then((m) => {
        if (live) setSessionMeta(m);
      })
      .catch(() => {
        if (live) setSessionMeta(null);
      });
    return () => {
      live = false;
    };
  }, [archive]);

  // Eager prewarm (row `eager-prewarm`, ADR-0018): once a selected model's meta
  // is ready and no turn is running, spawn the decode pool and build its staged
  // session NOW — off the first turn's TTFT. Best-effort (never load-bearing).
  // `onSend` awaits `prewarmRef` before its own `generate`, so the warm build and
  // the first real turn never build the session concurrently (which would race
  // the shared residency ledger). Fires once per archive.
  const prewarmRef = useRef<Promise<unknown> | null>(null);
  const prewarmedArchiveRef = useRef<string>("");
  useEffect(() => {
    if (!archive || !sessionMeta || running) return;
    if (prewarmedArchiveRef.current === archive) return;
    prewarmedArchiveRef.current = archive;
    prewarmRef.current = generate({ archive, prompt: "", warm: true }).catch(() => {});
  }, [archive, sessionMeta, running]);
  // On model switch, drop the previous model's prewarm handle: `onSend` awaits
  // `prewarmRef` before generating, and it must never await a DIFFERENT model's
  // warm. The newly-selected archive re-prewarms once its own meta loads above.
  useEffect(() => {
    return () => {
      prewarmRef.current = null;
    };
  }, [archive]);

  const selectedKnown = useMemo(
    () => (archive ? findKnownModel(archive, knownModels) : undefined),
    [archive, knownModels],
  );
  const turnSeparator =
    selectedKnown?.chatTurnSeparator ?? GENERIC_TURN_SEPARATOR;

  useEffect(() => {
    transcriptRef.current?.scrollTo({
      top: transcriptRef.current.scrollHeight,
      behavior: "smooth",
    });
  }, [messages, stream.text, inFlight]);

  async function onSend() {
    if (!archive || !prompt.trim() || running) return;
    const userText = prompt.trim();
    // Build the full transcript (cleaned assistant turns + new user turn) so
    // the model sees the conversation history. We clean assistant text to
    // strip leaked special tokens *before* feeding it back, otherwise stray
    // `<|im_end|>`/`</s>` would terminate the next turn early.
    const history: Message[] = [
      ...messages.map((m) =>
        m.role === "assistant"
          ? { role: "assistant" as const, text: cleanAssistantText(m.text) }
          : m,
      ),
      { role: "user", text: userText },
    ];
    // The PARAMETRIC path: render the conversation with the model's OWN chat
    // template (from its tokenizer_config.json), so any instruct model gets its
    // correct format + stop token — never a hard-coded per-model template. A
    // base model with no chat template falls back to the catalogue's
    // prompt-template plumbing. Session trimming (row session-window): the
    // model's own context is the only limit — a transcript that outgrows it
    // drops oldest turn pairs so the conversation continues rather than
    // dead-ending. Uses the model's own context + tokenizer (`sessionMeta`).
    const ctx = sessionMeta?.contextLength ?? null;
    const tok = sessionMeta?.tokenizer;
    let promptForModel: string;
    let stopStrings: string[];
    let promptTemplateForGen: string | undefined;

    const rendered = renderChat(history, sessionMeta);
    if (rendered) {
      // The model's own template — the rendered text IS the full prompt, so no
      // extra `{prompt}` wrap. Stop on the model's OWN eos (derived); the engine
      // also stops on the tokenizer's eos id, so no arbitrary label stop is
      // fabricated for a chat model that ships no eos string.
      promptForModel = rendered.prompt;
      stopStrings = rendered.stop;
      promptTemplateForGen = undefined;
      if (ctx && tok) {
        let working = history;
        try {
          while ((await countTokens(tok, promptForModel)) > ctx && working.length > 2) {
            working = working.slice(2);
            const r = renderChat(working, sessionMeta);
            if (!r) break;
            promptForModel = r.prompt;
          }
        } catch {
          // Counting unavailable: send untrimmed — the engine fails loud if the
          // prompt exceeds the model's context.
        }
      }
    } else {
      // Fallback: the catalogue's separator + prompt template (base models, or
      // a template that couldn't render).
      let workingHistory = history;
      promptForModel = buildMultiTurnPrompt(workingHistory, turnSeparator);
      const applyTemplate = (t: string | null | undefined, slot: string) =>
        t ? (t.includes("{prompt}") ? t.replace("{prompt}", slot) : t + slot) : slot;
      if (ctx && tok) {
        try {
          let tokens = await countTokens(tok, applyTemplate(selectedKnown?.promptTemplate, promptForModel));
          while (tokens > ctx && workingHistory.length > 2) {
            workingHistory = workingHistory.slice(2);
            promptForModel = buildMultiTurnPrompt(workingHistory, turnSeparator);
            tokens = await countTokens(tok, applyTemplate(selectedKnown?.promptTemplate, promptForModel));
          }
        } catch {
          // Counting unavailable: send untrimmed.
        }
      }
      // Prefer the model's OWN eos (derived), then a curated catalogue stop;
      // the generic User/Assistant stop is a last resort ONLY for a bare base
      // model with no eos, and it matches the generic separator we imposed.
      stopStrings = sessionMeta?.eosToken
        ? [sessionMeta.eosToken]
        : selectedKnown?.stop?.length
          ? selectedKnown.stop
          : ["\nUser:", "\nAssistant:"];
      promptTemplateForGen = selectedKnown?.promptTemplate ?? undefined;
    }

    // Append the user turn and persist it DIRECTLY (not only through the
    // messages effect), so it survives the component unmounting mid-generation:
    // navigating to Logs/Models to watch the stream must not lose the turn.
    const base: Message[] = [...messages, { role: "user", text: userText }];
    const storeKey = `hologram_chat:${archive}`;
    const persist = (msgs: Message[]) => {
      try {
        localStorage.setItem(storeKey, JSON.stringify(msgs));
      } catch {
        // Storage full/unavailable — the session still works in memory.
      }
    };
    setMessages(base);
    persist(base);
    setPrompt("");
    setRunning(true);
    // The in-flight completion streams into the module-level store (rendered as
    // a live trailing bubble), not into `messages` — so it accumulates whichever
    // route is mounted.
    chatStream.begin(archive);
    try {
      // Let any in-flight prewarm finish first: it and this turn share the worker
      // + the residency ledger, so they must build the session serially, never at
      // once. If prewarm already completed, this is an immediate no-op.
      await prewarmRef.current;
      await generate({
        archive,
        prompt: promptForModel,
        // No fixed cap: absent an explicit per-model setting, generation is
        // bounded by stop conditions, the remaining context, and Cancel.
        maxTokens: selectedKnown?.maxTokens,
        temperature,
        stop: stopStrings,
        // The model's OWN eos id (from its generation_config.json / config.json)
        // — a token-level stop that fires before detokenization, more reliable
        // than the decoded stop strings. Absent (or multi-eos) → the engine
        // falls back to the tokenizer's eos and the stop strings terminate.
        eos: sessionMeta?.eosTokenId,
        promptTemplate: promptTemplateForGen,
      });
      // Commit the final completion, persisting DIRECTLY. `generate` emits the
      // final `chat://line` synchronously before it resolves, so the store's
      // snapshot IS the completed text here. Writing localStorage (not relying
      // on a setState a torn-down component would ignore) is what makes the turn
      // survive a route change; committing before the composer re-enables also
      // stops the next prompt being built one flush short (the turn-3 truncation
      // the handshake reference gate caught).
      const finalText = chatStream.getSnapshot().text;
      const committed: Message[] = finalText
        ? [...base, { role: "assistant", text: finalText }]
        : base;
      setMessages(committed);
      persist(committed);
    } catch (e) {
      const errored: Message[] = [...base, { role: "assistant", text: `error: ${String(e)}` }];
      setMessages(errored);
      persist(errored);
    } finally {
      setRunning(false);
      chatStream.end();
    }
  }

  async function onCancel() {
    await cancelGeneration();
  }

  function onResetChat() {
    if (running) return;
    setMessages([]);
  }

  return (
    <div className="page chat">
      <div className="page-header">
        <h1>Chat</h1>
        <div className="row">
          <select
            value={archive}
            onChange={(e) => setArchive(e.target.value)}
            disabled={running}
            style={{ minWidth: 260 }}
          >
            {archives.length === 0 && <option value="">No compiled archives</option>}
            {archives.map((a) => (
              <option key={a.path} value={a.path}>
                {a.name}
              </option>
            ))}
          </select>
          <input
            type="number"
            value={temperature}
            step={0.1}
            min={0}
            max={2}
            onChange={(e) => setTemperature(Number(e.target.value))}
            style={{ width: 70 }}
            disabled={running}
            title="temperature"
          />
          <button
            onClick={onResetChat}
            disabled={running || messages.length === 0}
            title="Clear conversation history"
          >
            New chat
          </button>
        </div>
      </div>

      <div className="transcript" ref={transcriptRef}>
        {messages.length === 0 && !inFlight ? (
          <div className="empty">Pick an archive and send a prompt.</div>
        ) : (
          <>
            {messages.map((m, i) => (
              <div key={i} className={`bubble ${m.role}`}>
                <div className="role">{m.role}</div>
                <MessageBody
                  text={m.role === "assistant" ? cleanAssistantText(m.text) : m.text}
                />
              </div>
            ))}
            {/* The live in-flight completion (from the module store), rendered
                whether or not this route was mounted when it started. Before the
                first token it shows the honest startup narration. */}
            {inFlight && (
              <div className="bubble assistant">
                <div className="role">assistant</div>
                {streamingText ? (
                  <MessageBody text={streamingText} />
                ) : (
                  <div className="md">{stream.status ? `${stream.status} …` : "…"}</div>
                )}
              </div>
            )}
          </>
        )}
      </div>

      <div className="composer">
        <textarea
          placeholder="Ask anything…  (Cmd/Ctrl+Enter to send)"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
              e.preventDefault();
              onSend();
            }
          }}
          disabled={running || !archive}
        />
        {running ? (
          <button onClick={onCancel}>Cancel</button>
        ) : (
          <button onClick={onSend} disabled={!archive || !prompt.trim()}>
            Send
          </button>
        )}
      </div>
    </div>
  );
}
